# Generated by Django 3.1.7 on 2021-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('github_id', models.CharField(blank=True, max_length=64, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter_id', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
